- name:
  os_security_group:
    name: "{{ item.name }}"
    description: "{{ item.description|default(omit) }}"
  with_items: "{{ security_groups }}"

- name:
  os_security_group_rule:
    state: present
    security_group: "{{ item.0.name }}"
    protocol: "{{ item.1.protocol|default(omit) }}"
    remote_ip_prefix: "{{ item.1.remote_ip_prefix|default(omit) }}"
    port_range_min: "{{ item.1.port_range_min|default(omit) }}"
    port_range_max: "{{ item.1.port_range_max|default(omit) }}"
    direction: "{{ item.1.direction|default(omit) }}"
    ethertype: "{{ item.1.ethertype|default(omit) }}"
  with_subelements:
      - "{{ security_groups }}"
      - rules
 # os_security_group_rule is not idempotent, if the rule exists
 # the module returns error
  ignore_errors: true
