---
zuul_api: "https://review.rdoproject.org/zuul/api/"
pull_registry: "trunk.registry.rdoproject.org"
push_registry: "quay.io"
entries:
  - name: "master"
    release: "master"
    job_name: "periodic-tripleo-ci-build-containers-ubi-8-push"
    api_entry: "https://trunk.rdoproject.org/api-centos8-master-uc"
    from_namespace: "tripleomaster"
    to_namespace: "tripleomaster"
  - name: "mastercentos9"
    release: "mastercentos9"
    job_name: "periodic-tripleo-ci-build-containers-centos-9-push-master"
    api_entry: "https://trunk.rdoproject.org/api-centos9-master-uc"
    from_namespace: "tripleomastercentos9"
    to_namespace: "tripleomastercentos9"
  - name: "wallaby"
    release: "wallaby"
    job_name: "periodic-tripleo-ci-build-containers-ubi-8-push-wallaby"
    api_entry: "https://trunk.rdoproject.org/api-centos8-wallaby"
    from_namespace: "tripleowallaby"
    to_namespace: "tripleowallaby"
  - name: "wallabycentos9"
    release: "wallabycentos9"
    job_name: "periodic-tripleo-ci-build-containers-centos-9-push-wallaby"
    api_entry: "https://trunk.rdoproject.org/api-centos9-wallaby"
    from_namespace: "tripleowallabycentos9"
    to_namespace: "tripleowallabycentos9"
  - name: "zedcentos9"
    release: "zedcentos9"
    job_name: "periodic-tripleo-ci-build-containers-ubi-9-quay-push-zed"
    api_entry: "https://trunk.rdoproject.org/api-centos9-zed"
    from_namespace: "tripleozedcentos9"
    to_namespace: "tripleozedcentos9"
  - name: "victoria"
    release: "victoria"
    job_name: "periodic-tripleo-ci-build-containers-ubi-8-push-victoria"
    api_entry: "https://trunk.rdoproject.org/api-centos8-victoria"
    from_namespace: "tripleovictoria"
    to_namespace: "tripleovictoria"
  - name: "ussuri"
    release: "ussuri"
    job_name: "periodic-tripleo-ci-build-containers-ubi-8-push-ussuri"
    api_entry: "https://trunk.rdoproject.org/api-centos8-ussuri"
    from_namespace: "tripleoussuri"
    to_namespace: "tripleoussuri"
  - name: "train8"
    release: "train8"
    job_name: "periodic-tripleo-ci-build-containers-ubi-8-push-train"
    api_entry: "https://trunk.rdoproject.org/api-centos8-train"
    from_namespace: "tripleotraincentos8"
    to_namespace: "tripleotraincentos8"
