---
dlrnapi_protocol: "https"
dlrnapi_host: "trunk.rdoproject.org"
dlrnapi_endpoint:
  centos8:
    master: api-centos8-master-uc
    ussuri: api-centos8-ussuri
    train: api-centos8-train
  centos7:
    train: api-centos8-train
    stein: api-centos-stein
    rocky: api-centos-rocky
    queens: api-centos-queens
  redhat8:
    rhos-17: api-rhel8-osp17

dlrn_baseurl:
  centos8:
    master: centos8-master
    ussuri: centos8-ussuri
    train: centos8-train
  centos7:
    train: centos7-train
    stein: centos7-stein
    rocky: centos7-rocky
    queens: centos7-queens
  redhat8:
    rhos-17: rhel8-osp17
dlrnapi_url: "{{ dlrnapi_protocol }}://{{ dlrnapi_host }}/{{ dlrnapi_endpoint[distro][osp_release|default(release)] }}"
dlrn_hash_baseurl: "{{ dlrnapi_protocol }}://{{ dlrnapi_host }}/{{ dlrn_baseurl[distro][osp_release|default(release)] }}"
distro: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}"
