- name: Teardown # noqa 301
  shell: |
    source /home/{{ promoter_user }}/promoter_venv/bin/activate
    /home/{{ promoter_user }}/promoter_venv/bin/python3 \
        {{ ci_config_remote_src_dir }}/ci-scripts/dlrnapi_promoter/stage.py \
            teardown --scenes dlrn,registries,containers
