---
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: >-
      ssh
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -o Compression=no
      -o TCPKeepAlive=yes
      -o VerifyHostKeyDNS=no
      -o ForwardX11=no
      -o ForwardAgent=no
      {instance}
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: instance

provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: /tmp/molecule/facts
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_hostname: tester
            ansible_python_interpreter: ${MOLECULE_INTERPRETER:-/home/zuul/test-python/bin/python}

scenario:
  name: tripleo-common-integration
  test_sequence:
    - prepare
    - converge
    - verify
