---
main:
  distro_name: centos
  distro_version: 8
  release: master
  api_url: https://trunk.rdoproject.org/api-centos-master-uc
  username: ciuser
  dry_run: no

promote_from:
  current-tripleo-compute: tripleo-ci-testing
  current-tripleo-security: tripleo-ci-testing

current-tripleo-compute:
  - periodic-tripleo-ci-centos-8-standalone-compute-master

current-tripleo-security:
  - periodic-tripleo-ci-centos-8-standalone-security-master
