---
main:
  distro_name: centos
  distro_version: 8
  release: master
  api_url: https://trunk.rdoproject.org/api-centos8-master-uc
  username: ciuser
  dry_run: no

promote_from:
  component-ci-testing: promoted-components

component-ci-testing:
  baremetal:
    - periodic-tripleo-ci-centos-8-standalone-baremetal-master
  cinder:
    - periodic-tripleo-ci-centos-8-standalone-cinder-master
  clients:
    - periodic-tripleo-ci-centos-8-standalone-clients-master
  cloudops:
    - periodic-tripleo-ci-centos-8-standalone-cloudops-master
  common:
    - periodic-tripleo-ci-centos-8-standalone-common-master
  compute:
    - periodic-tripleo-ci-centos-8-standalone-compute-master
  glance:
    - periodic-tripleo-ci-centos-8-standalone-glance-master
  manila:
    - periodic-tripleo-ci-centos-8-standalone-manila-master
  network:
    - periodic-tripleo-ci-centos-8-standalone-network-master
  octavia:
    - periodic-tripleo-ci-centos-8-standalone-octavia-master
  security:
    - periodic-tripleo-ci-centos-8-standalone-security-master
  swift:
    - periodic-tripleo-ci-centos-8-standalone-swift-master
  tempest:
    - periodic-tripleo-ci-centos-8-standalone-tempest-master
  tripleo:
    - periodic-tripleo-ci-centos-8-standalone-tripleo-master
  ui:
    - periodic-tripleo-ci-centos-8-standalone-ui-master
