---
main:
  distro_name: centos
  distro_version: 8
  release: master
  api_url: https://trunk.rdoproject.org/api-centos8-master-uc
  username: ciuser
  dry_run: no

# promote_from is not used in component promotion using promote-hash
promote_from:
  promoted-components: component-ci-testing

# target promotion label now has a nested list of criteria jobs
# for each component
promoted-components:
  baremetal:
    - periodic-tripleo-ci-centos-8-standalone-baremetal-master
    # future fs001
  cinder:
    - periodic-tripleo-ci-centos-8-standalone-cinder-master
    - periodic-tripleo-ci-centos-8-scenario001-standalone-cinder-master
    - periodic-tripleo-ci-centos-8-scenario004-standalone-cinder-master
  clients:
    - periodic-tripleo-ci-centos-8-standalone-clients-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-clients-master
  cloudops:
    - periodic-tripleo-ci-centos-8-standalone-cloudops-master
    - periodic-tripleo-ci-centos-8-scenario001-standalone-cloudops-master
    - periodic-tripleo-ci-centos-8-scenario002-standalone-cloudops-master
  common:
    - periodic-tripleo-ci-centos-8-standalone-common-master
    - periodic-tripleo-ci-centos-8-scenario001-standalone-common-master
    - periodic-tripleo-ci-centos-8-scenario002-standalone-common-master
    - periodic-tripleo-ci-centos-8-scenario003-standalone-common-master
    - periodic-tripleo-ci-centos-8-scenario004-standalone-common-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-common-master
  compute:
    - periodic-tripleo-ci-centos-8-standalone-compute-master
    - periodic-tripleo-ci-centos-8-standalone-full-tempest-compute-master
  glance:
    - periodic-tripleo-ci-centos-8-scenario001-standalone-glance-master
    - periodic-tripleo-ci-centos-8-scenario002-standalone-glance-master
    - periodic-tripleo-ci-centos-8-scenario003-standalone-glance-master
    - periodic-tripleo-ci-centos-8-scenario004-standalone-glance-master
  manila:
    - periodic-tripleo-ci-centos-8-scenario004-standalone-manila-master
  network:
    - periodic-tripleo-ci-centos-8-standalone-network-master
    - periodic-tripleo-ci-centos-8-scenario007-standalone-network-master
    - periodic-tripleo-ci-centos-8-scenario010-standalone-network-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-network-master
  octavia:
    - periodic-tripleo-ci-centos-8-standalone-octavia-master
    - periodic-tripleo-ci-centos-8-scenario007-standalone-octavia-master
    - periodic-tripleo-ci-centos-8-scenario010-standalone-octavia-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-octavia-master
  security:
    - periodic-tripleo-ci-centos-8-standalone-security-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-security-master
  swift:
    - periodic-tripleo-ci-centos-8-scenario002-standalone-swift-master
  tempest:
    - periodic-tripleo-ci-centos-8-standalone-tempest-master
    - periodic-tripleo-ci-centos-8-standalone-full-tempest-tempest-master
  tripleo:
    - periodic-tripleo-ci-centos-8-standalone-tripleo-master
    - periodic-tripleo-ci-centos-8-multinode-1ctlr-featureset010-tripleo-master
    # possible fs01
  ui:
    - periodic-tripleo-ci-centos-8-standalone-ui-master
