---
server_name: "10.19.113.130 tripleo-cockpit.usersys.redhat.com"
cockpit_server_name: internal-cockpit.tripleo.org
cockpit_url: "http://10.19.113.130/d/9DmvErfZz/cockpit"
down_repo_path: "~/additional-repo-master"
down_repo_url: https://code.engineering.redhat.com/gerrit/openstack/rrcockpit
down_repo_branch: master
